Update README.md
Quatro-Java-Corp/Quatro pull request #14
Opened 2023-04-05 10:47 UTC by student317

2023-04-05 11:07 UTC, Spajro requested changes

2023-04-05 11:07 UTC, Spajro commented on README.md
> +* Pole powierzchni
Wygląda jakbyś wpisał polecenie do p3 w środku p2

2023-04-05 11:24 UTC, Spajro approved these changes

2023-04-06 08:28 UTC, MarcinBieganek approved these changes

2023-04-06 09:11 UTC, merged