Dodanie klas obsługujących żadania tworzenia figur
Quatro-Java-Corp/Quatro pull request #15
Opened 2023-04-05 19:17 UTC by wilinska

Dodanie klas InputHandler i ShapeService
Usunięcie podziału na krótsze i dłuższe boki/przekątne

2023-04-06 08:28 UTC, Spajro requested changes
Dwa commity zdublowane z #13

2023-04-06 08:28 UTC, Spajro commented on src/main/java/Figure.java
> +    String toString();
Nie potrzebujemy definiować toString() w interfejsie

2023-04-06 08:28 UTC, Spajro commented on src/main/java/InputHandler.java
> +            return name;
Możemy zrobić od razu return nie potrzebujemy zmiennej

2023-04-06 08:28 UTC, Spajro commented on src/main/java/ShapeService.java
> +        });
Nadmiarowy nawias dookoła switcha

2023-04-06 08:28 UTC, Spajro commented on src/main/java/ShapeService.java
> +    };
Nadmiarowe średniki

2023-04-06 08:28 UTC, Spajro commented on src/test/java/InputHandlerTest.java
> +            assertEquals(10, 9);
?

2023-04-06 08:28 UTC, Spajro commented on src/test/java/InputHandlerTest.java
> +    public void shouldCreateRectangleWithShortSideAndLongSideAndCalculateOtherParameters() throws Exception {
Zastanawiam się, czy testy powinny rzucać checked wyjątki

2023-04-06 10:51 UTC, wilinska commented on src/main/java/Figure.java
> +    String toString();
potrzebujemy, żeby móc wywołać na Figure toString i ją wyświetlić bez rzutowania na konkretną figurę

2023-04-06 10:58 UTC, wilinska commented on src/test/java/InputHandlerTest.java
> +    public void shouldCreateRectangleWithShortSideAndLongSideAndCalculateOtherParameters() throws Exception {
A jak dobrze failować test z uzyciem try catch? dać fail() w catch?

2023-04-06 17:01 UTC, Spajro commented on src/main/java/Figure.java
> +    String toString();
Metoda toString() jest zadeklarowana w klasie Object która jest dziedziczona przez każdą inną klasę w javie więc każda klasa ma metodę toString i można z niej korzystać bez dodatkowego deklarowania w interfejsie

2023-04-06 17:24 UTC, Spajro commented on src/test/java/InputHandlerTest.java
> +            assertEquals(10, 9);
Ze zaktualizowanym junitem: assertDoesNotThrow( () -> {  //kod testu  } )

2023-04-06 17:25 UTC, Spajro commented on src/test/java/InputHandlerTest.java
> +    public void shouldCreateRectangleWithShortSideAndLongSideAndCalculateOtherParameters() throws Exception {
Napisałem wyżej, swoją drogą jak zrobiłaś try catch'a to throws Exception w deklaracji jest zbędne bo nie może polecieć skoro je łapiesz

2023-04-07 07:03 UTC, student317 commented
Aj zamiast zrobić nowego  branch'a wrzuciłem tu

2023-04-07 09:40 UTC, Spajro requested changes

2023-04-07 09:40 UTC, Spajro commented on src/main/java/Main.java
> +        ArrayList<Figure> figueList = new ArrayList<Figure>();
Literówka

2023-04-07 09:40 UTC, Spajro commented on src/main/java/Main.java
> +                Collections.sort(figueList, (Figure a, Figure b) -> a.getSurfaceArea() < b.getSurfaceArea() ? -1 : 1);
Zamiast Collections.sort(figureList ...) można zrobić figureList.sort(...), krótszy kod.

2023-04-07 09:40 UTC, Spajro commented on src/main/java/Main.java
> +                Collections.sort(figueList, (Figure a, Figure b) -> a.getSurfaceArea() < b.getSurfaceArea() ? -1 : 1);
Moglibyśmy sortować przed wypisywaniem wszystkich zamiast po dodaniu nowej

2023-04-07 09:48 UTC, student317 commented on src/main/java/Main.java
> +                Collections.sort(figueList, (Figure a, Figure b) -> a.getSurfaceArea() < b.getSurfaceArea() ? -1 : 1);
Zmienione

2023-04-07 09:48 UTC, student317 commented on src/main/java/Main.java
> +                Collections.sort(figueList, (Figure a, Figure b) -> a.getSurfaceArea() < b.getSurfaceArea() ? -1 : 1);
Skrócone

2023-04-07 09:48 UTC, student317 commented on src/main/java/Main.java
> +        ArrayList<Figure> figueList = new ArrayList<Figure>();
Poprawione

2023-04-07 10:06 UTC, Spajro commented on src/test/java/InputHandlerTest.java
> +    public void shouldCreateRectangleWithShortSideAndLongSideAndCalculateOtherParameters() throws Exception {
Dalej mamy niepotrzebne "throws Exception"

2023-04-07 10:06 UTC, Spajro commented on src/test/java/InputHandlerTest.java
> +        assertEquals(r.getSurfaceArea(), AREA_VALUE, DELTA);
Przechodzi Ci ten test lokalnie? Bo u mnie failuje

2023-04-07 10:41 UTC, Spajro approved these changes

2023-04-07 10:42 UTC, merged