Podział fabryki na pracowników tworzących figury
Quatro-Java-Corp/Quatro pull request #27
Opened 2023-04-14 19:04 UTC by wilinska

Przeniesienie odpowiedzialności tworzenia obiektów do Workerów fabryki.
Odseparowanie ShapeFactory od odpowiedzialności o tym jak tworzyć obiekty, jedynie dodajemy do niej w konstruktorze odpowiednich workerów.

Potencjalne dodatkowe zmiany:
1. Usunięcie enuma ShapeFactory - wydaje mi się, że już nie jest potrzebne, możemy spokojnie przekazać dalej String

Pytania:
Czy można enum nazw parametrów przenieść w jakieś sensowniejsze mniejsce, czy tak jest ok?

2023-04-15 11:16 UTC, Spajro requested changes

2023-04-15 11:16 UTC, Spajro commented on src/main/java/factory/ShapeFactoryWorker.java
> +    Shape create(String shapeName, List<Entry<ArgumentType, Double>> args) throws Exception;
Nie bylibyśmy w stanie rozwiązać tego w taki sposób, żeby nie musieć przekazywać do workera shapeName? Imho za użycie poprawnego workera powinna odpowiadać fabryka

2023-04-15 11:16 UTC, Spajro commented on src/main/java/shapes/Circle.java
> +    public static final double numberOfArguments = 1;
Nie lepiej byłoby trzymać  tą informację w workerze, skoro mamy i tak worker per shape?

2023-04-15 20:35 UTC, wilinska commented on src/main/java/factory/ShapeFactory.java
> +    }
taka funkcja często jest publiczna i umożliwia dodawanie workerów przez klienta

2023-04-15 20:39 UTC, wilinska commented on src/main/java/factory/ShapeFactory.java
> +
ale wtedy fabryka musi wiedzieć, że shape ma swoją nazwę

2023-04-15 20:41 UTC, wilinska commented on src/main/java/shapes/Circle.java
> +    public static final double numberOfArguments = 1;
wczesniej tak bylo, nie byłam pewna, kto powinien być odpowiedzialny za trzymanie tego, mogę przerzucić

2023-04-17 10:43 UTC, student317 approved these changes

2023-04-17 14:14 UTC, Spajro commented on src/main/java/factory/ShapeFactory.java
> +    }
Nie mamy takie przypadku i bym się go raczej nie spodziewał ale myślę, że możemy zostawić jak jest

2023-04-17 14:14 UTC, Spajro approved these changes

2023-04-17 16:24 UTC, merged