Dodanie klas: figura koło kwadrat
Quatro-Java-Corp/Quatro pull request #3
Opened 2023-03-22 11:36 UTC by student317

2023-03-22 11:44 UTC, Spajro requested changes

2023-03-22 11:44 UTC, Spajro commented on src/main/java/Circle.java
> +    public Circle(double value, int which) throws Exception {
Moglibyśmy uzyc enuma zamiast inta, zeby przekazac czym jest value. Byłoby to bardziej czytelne

2023-03-22 11:44 UTC, Spajro commented on src/main/java/Figure.java
> +public class Figure {
Nie lepszy byłby interfejs z metodą getArea()?

2023-03-22 11:44 UTC, Spajro commented on src/main/java/Circle.java
> +    protected double radius;
W sumie to nie musimy trzymać wszystkich parametrów, wystarczy trzymać radius i resztę obliczać on-demand.

2023-03-22 11:44 UTC, Spajro commented on src/main/java/Square.java
> +    protected double diagonalLength;
Tez mozemy to obliczać on demand

2023-03-22 11:44 UTC, Spajro commented on src/main/java/Square.java
> +    public Square(double value, int which) throws Exception {
Tak jak dla Circle

2023-03-22 11:44 UTC, Spajro commented on src/main/java/Circle.java
> +    }
Nie lepsze byłoby dodanie getterów zamiast takiego toStringa jeśli chodzi o zwracanie wartosci?

2023-03-22 11:48 UTC, student317 commented on src/main/java/Circle.java
> +    }
getery i settery można dodać ale tostringa bym zostawił

2023-03-22 11:50 UTC, student317 commented on src/main/java/Circle.java
> +    public Circle(double value, int which) throws Exception {
Dobry pomysł

2023-03-22 12:02 UTC, Spajro commented on src/main/java/Circle.java
> +    }
To zostawmy toStringa, setterów bym nie dodawał i zrobił zmienne final, bo te klasy mogłby być immutable

2023-03-22 17:38 UTC, student317 commented on src/main/java/Circle.java
> +    }
Wysłałem nowego commita

2023-03-22 18:41 UTC, Spajro commented on src/main/java/Circle.java
> +    public Circle(double value, int which) throws Exception {
Value w enumie chyba nie potrzebujemy i nie wykorzystujemy

2023-03-22 18:42 UTC, Spajro commented on src/main/java/Circle.java
> +    protected double radius;
Zastanowiłeś się nad tym moze? Skróciłoby to dodatkowo znacznie długość konstruktorów

2023-03-22 18:43 UTC, Spajro commented on src/main/java/Circle.java
> +    protected double radius;
Zmienną moglibyśmy zrobić tez jako final zeby miec explicite immutability

2023-03-22 19:44 UTC, student317 commented on src/main/java/Circle.java
> +    protected double radius;
Nie jestem przekonany, przy niektórych wartościach mogło by się okazać że podane pole przeliczone na promień a potem na pole nie było by sobie równe

2023-03-22 19:54 UTC, Spajro commented on src/main/java/Circle.java
> +    protected double radius;
Masz rację, prawie na pewno taki problem się pojawi, ponieważ operujemy na doublach. Z drugiej strony, ponieważ operujemy na doublach to i tak musimy porównywać +-epsilon bo błędy zaokrągleń pojawią się i tak, jeśli nie przy takim przeliczaniu to przy zwykłym obliczaniu wartości nie podanych. Od błędów zaokrągleń w tego typu obliczeniach nie uciekniemy a jednocześnie taka zmiana poprawi znacznie czytelność konstruktorów, bo chwilowo mamy wielokrotnie zduplikowany kod.

2023-03-22 20:51 UTC, Spajro commented
Jakbyś tylko jeszcze mógł kod sformatować (ctrl+alt+l w idei w obu klasach) to dla mnie będzie git.

2023-03-22 21:05 UTC, Spajro commented on src/main/java/Circle.java
> +
Nadmiarowa spacja

2023-03-22 21:05 UTC, Spajro commented on src/main/java/Circle.java
> +
Nadmiarowa spacja

2023-03-22 21:05 UTC, Spajro commented on src/main/java/Circle.java
> +        return "Circle{" + "circuit=" + String.valueOf(getCircuit()) + ", diameter=" + String.valueOf(getDiameter()) + ", radius=" + radius + ", surfaceArea=" + String.valueOf(getSurfaceArea()) + '}'
Potrzebujemy tego String.valueOf()?

2023-03-22 21:05 UTC, Spajro commented on src/main/java/Circle.java
> +        }
Nie byłby czytelniejszy ten switch z arrowami zamiast breaków?

2023-03-22 21:05 UTC, Spajro commented on src/main/java/Square.java
> +
Dwie nadmiarowe spacje i ten case ze switchem co w Square

2023-03-22 21:05 UTC, Spajro commented on src/main/java/Circle.java
> +
Tez nadmiarowa spacja

2023-03-23 07:20 UTC, student317 commented on src/main/java/Circle.java
> +
Przepchnijmy tego push'a i poprostu z commituj takie wizualne poprawki bo ja nie widzę tych spacji nawet

2023-03-23 07:22 UTC, student317 commented on src/main/java/Circle.java
> +        return "Circle{" + "circuit=" + String.valueOf(getCircuit()) + ", diameter=" + String.valueOf(getDiameter()) + ", radius=" + radius + ", surfaceArea=" + String.valueOf(getSurfaceArea()) + '}'
A co java rozpoznaje typy i double przy konkatenacji sam się konwertuje na stringa? możliwe że tak jest to może i lepiej skrócić.

2023-03-23 08:21 UTC, Spajro commented on src/main/java/Circle.java
> +
Ok

2023-03-23 18:44 UTC, wilinska approved these changes

2023-03-23 18:51 UTC, Spajro approved these changes

2023-03-23 18:51 UTC, merged