P4 command factoryv2
Quatro-Java-Corp/Quatro pull request #30
Opened 2023-04-19 08:22 UTC by student317

2023-04-19 17:48 UTC, Spajro requested changes
Mam trzy ogólne postulaty:
1. commany i CommandFactory umiesciłbym w pakiecie command
2. Implementacje Command mogłby nie mieć prefixu Command w nazwie
3. Implementacje Command mogłby być package-private, poza CommandFactory nie potrzebujemy wiedzieć jaką konkretną implementację command mamy, po prostu ją wykonujemy

2023-04-19 17:48 UTC, Spajro commented on src/main/java/InputHandler.java
> +*/
Tego nie powinno chyba być

2023-04-21 19:42 UTC, Spajro requested changes
Imho ShapeRepository nie powinno znajdować się w /shapes.
Wycofałym się również z pakietu /other

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Showfigures.java
> +    private static final String NO_NEED_ARGUMENTS = "This function don't need any arguments";
zbędna zmienna

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Showfigures.java
> +    ShapeRepository shapeRepo;
```suggestion
    private final ShapeRepository shapeRepo;
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Showfigures.java
> +            shapeRepo.getShapes().forEach(System.out::println);
```suggestion
            shapeRepo.print();
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Sort.java
> +class Sort implements  Command{
```suggestion
class Sort implements Command{
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Sort.java
> +    private ShapeRepository shapeRepo;
```suggestion
    private final ShapeRepository shapeRepo;
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Sort.java
> +    private String[] args;
```suggestion
    private final String[] args;
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Sort.java
> +    private final ComparatorFactory comparatorFactory=new ComparatorFactory();
```suggestion
    private final ComparatorFactory comparatorFactory = new ComparatorFactory();
    
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/other/InputHandler.java
> +    private final ComparatorFactory comparatorFactory=new ComparatorFactory();
Nieużywana zmienna

2023-04-21 19:42 UTC, Spajro commented on src/main/java/other/InputHandler.java
> +    private static final String UNKNOWN_FUNCTION = "Unknown function";
Nieużywane zmienne

2023-04-21 19:42 UTC, Spajro commented on src/main/java/other/InputHandler.java
> +                Command command = commandFactory.createCommand(commandName,args,figureList);
```suggestion
                Command command = commandFactory.createCommand(commandName, args, figureList);
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/other/InputHandler.java
> +    }
```suggestion
    }
    
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/CommandFactory.java
> +        return new Showfigures(shapeRep);
brak taba

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Showfigures.java
> +class Showfigures implements Command{
```suggestion
class ShowFigures implements Command{
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Circumscribed.java
> +     private ShapeRepository figureList;
```suggestion
     private final ShapeRepository figureList;
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Circumscribed.java
> +     private String[] args;
```suggestion
     private final String[] args;
```

2023-04-21 19:42 UTC, Spajro commented on src/main/java/command/Add.java
> +            Shape shape = InputHandler.createFigureWithArguments(Arrays.copyOfRange(args, 1, args.length));
Imho ta metoda mogłaby nie być statyczna tylko przekazywalibyśmy inputHandler w konstruktorze

2023-04-21 19:45 UTC, Spajro commented on src/main/java/command/Add.java
> +            Shape shape = InputHandler.createFigureWithArguments(Arrays.copyOfRange(args, 1, args.length));
W dodatku musimy kopiować  tablicy.

2023-04-21 19:46 UTC, Spajro commented
Jeszcze jedna moja propozycja to przekazywać `List<String> args` zamiast `String[] args`.

2023-04-25 08:22 UTC, student317 commented
ShapeRepository musi być w jakimś pakiecie abyśmy mogli się do niego odnosić z innych pakietów, dlatego zrobiłem też pakiet "other" żeby móc się odnosić do nich jakoś i je importować w pakiecie command

2023-04-25 11:59 UTC, Spajro commented
Ok, fair point.
W #32 zrobiłem /repository/ShapeRepository i /repository/ComparatorFactory, to może /input/InputHandler?

2023-04-26 07:19 UTC, Spajro approved these changes

2023-04-26 07:29 UTC, MarcinBieganek approved these changes

2023-04-26 07:29 UTC, merged