P7 new shape
Quatro-Java-Corp/Quatro pull request #43
Opened 2023-05-11 14:57 UTC by student317

2023-05-11 15:24 UTC, Spajro requested changes

2023-05-11 15:24 UTC, Spajro commented on src/main/java/factory/ShapeFactory.java
> +        side, diagonal, area, radius, diameter, circuit, height, base, cathetus, hypotenuse, semiminoraxis, semimajoraxis, shortbase,longbase
```suggestion
        side, diagonal, area, radius, diameter, circuit, height, base, cathetus, hypotenuse, semiminoraxis, semimajoraxis, shortbase, longbase
```

2023-05-11 15:24 UTC, Spajro commented on pom.xml
> +            </plugin>
Do czego tego potrzebujemy?

2023-05-11 15:24 UTC, Spajro commented on README.md
> +2 z 10 przypadków: (podstawa 1-2, ramię, pole powierzchni) nie muszą być rozpatrywane
Zdublowana zmiana z #42

2023-05-11 15:24 UTC, Spajro commented on src/main/java/factory/IsoscelesTrapezoidFactoryWorker.java
> +        return switch (arg1.getKey().toString() + "|" + arg2.getKey().toString() + "|" + arg3.getKey().toString() ){
```suggestion
        var arg3 = args.get(2);
        
        return switch (arg1.getKey().toString() + "|" + arg2.getKey().toString() + "|" + arg3.getKey().toString() ){
```

2023-05-11 15:24 UTC, Spajro commented on src/main/java/shapes/IsoscelesTrapezoid.java
> +    } //done
```suggestion
    }
```

2023-05-11 15:24 UTC, Spajro commented on src/main/java/shapes/IsoscelesTrapezoid.java
> +    } //done
```suggestion
    }
```

2023-05-11 15:24 UTC, Spajro commented on src/main/java/shapes/IsoscelesTrapezoid.java
> +    } //done
```suggestion
    }
```

2023-05-11 15:24 UTC, Spajro commented on src/main/java/shapes/IsoscelesTrapezoid.java
> +    public double getHeight() {return height;}
Przydałyby się linie odstępu między metodami i moglibyśmy je rozwinąć z one-linerów bo takiej konwencji się trzymamy w innych figurach

2023-05-11 15:24 UTC, Spajro commented on src/main/java/shapes/IsoscelesTrapezoid.java
> +            return Optional.of(Circle.withRadius(height/2));
```suggestion
        if (shortBaseLength+longBaseLength != 2* getSide()) {
            return Optional.empty();
        }
        else {
            return Optional.of(Circle.withRadius(height/2));
        }
```

2023-05-15 16:39 UTC, wilinska requested changes
Napisałam podstawowe testy i nie wszystkie przechodzą.
Brakuje obsługi przypadków nieprawidłowości.
Standardowo mamy do czynienia z segmentami, które są trójkatami prostokątnymi, więc trzeba pilnować, żeby zgadzały się przyprostokątne i przeciwprostokątne - tutaj to będzie side i long_base/2 + jakaś delta (zeby był trapez a nie trójkąt), no i height.

2023-05-15 16:39 UTC, wilinska commented on src/main/java/shapes/IsoscelesTrapezoid.java
> +                ", SideLength=" + Format.format(getSurfaceArea()) +
getSurfaceArea -> getSide()

2023-05-15 16:39 UTC, wilinska requested changes
Napisałam podstawowe testy i nie wszystkie przechodzą.
Brakuje obsługi przypadków nieprawidłowości.
Standardowo mamy do czynienia z segmentami, które są trójkatami prostokątnymi, więc trzeba pilnować, żeby zgadzały się przyprostokątne i przeciwprostokątne - tutaj to będzie side i long_base/2 + jakaś delta (zeby był trapez a nie trójkąt), no i height.

2023-05-16 13:39 UTC, wilinska approved these changes

2023-05-16 19:58 UTC, Spajro requested changes

2023-05-16 19:58 UTC, Spajro commented on src/main/java/command/SaveToFile.java
> +public class SaveToFile implements Command {
Nie wystarczyłoby same `Save` jako nazwa klasy?

2023-05-16 19:58 UTC, Spajro commented on src/main/java/command/SaveToFile.java
> +            }
Jak na moje zrozumenie współbieżności to ten kod nie jest asynchroniczny.
Imho wystarczyły jeden wątek w którym konstruowalibyśmy jednego Stringa i zapisywali go do pliku.

2023-05-16 19:58 UTC, Spajro commented on src/main/java/repository/ShapeRepository.java
> +    }
Niekoniecznie musimy to zmieniać, ale pętlę po wszystkich elementach z repozytorium można zaimplementować bez tej metody

2023-05-16 21:44 UTC, student317 commented on src/main/java/command/SaveToFile.java
> +            }
Wydaje mi się że po to ma to być asynchroniczne żeby można było tego w jakiś sposób "doświadczyć"

2023-05-16 21:45 UTC, student317 commented on src/main/java/repository/ShapeRepository.java
> +    }
To niech zostanie, bo nie widzę jak. Może potem się to zmieni

2023-05-16 22:38 UTC, Spajro commented on src/main/java/repository/ShapeRepository.java
> +    }
To zostawmy, bardziej jako ciekawostka to `ShapeRepository.get` da nam pustego optionala jak index będzie większy od size i można to wykorzystać jako warunek pętli

2023-05-16 22:43 UTC, Spajro commented on src/main/java/command/SaveToFile.java
> +            }
Hm. Wydaje mi się, że liczba wątków liniowo proporcjonalna do liczby elementów w repozytorium, która nie jest de facto ograniczona, daje nam bardzo duży narzut na pamięć i czas wykonania. Dla bardzo dużej ilości elementów poświęcimy bardzo dużo czasu na tworzenie takiej ilości wątków gdzie celem podejścia asynchronicznego jest właśnie uniknięcie tego.

2023-05-17 06:37 UTC, Spajro commented on src/main/java/command/Save.java
> +    private PrintWriter writer;
Wykorzystujemy zmienny writer i lock?

2023-05-17 06:42 UTC, Spajro approved these changes

2023-05-17 06:43 UTC, merged