Dodanie dwujęzycznośći z pominięciem toString figur
Quatro-Java-Corp/Quatro pull request #54
Opened 2023-05-26 18:26 UTC by wilinska

Pomysł na dodanie dwujęzyczności jest następujący:
* dodajemy parser, który przetłumaczy komendy na język angielski, w ten sposób odpowiedzialność jest w parserze, a nie w fabrykach, parser jest przygotowany nawet do większej liczby języków, potencjalnie
* informacja o aktualnym języku jest dostępna w statycznej klasie Language
* język zmieniamy komendą
* potrzebna była zmiana komunikatów dla błędów, na ten moment można to zrobić w prosty sposób z wykorzystaniem instrukcji warunkowej

Dodałam testy zmiany języka oraz pojednyczy test tworzenia kwadratu dla wersji językowej polskiej
Zależy mi na dostarczeniu osobno zmian do samych figur, żeby uniknąć późniejszych konfliktów. Więc jeżeli to będzie ok

2023-05-26 21:04 UTC, Spajro requested changes

2023-05-26 21:04 UTC, Spajro commented on src/main/java/input/Parser.java
> +    public static final Map<String, ArgumentType> ArgumentTypeDictionaryPL = Map.ofEntries(
Mogłoby być private tho

2023-05-26 21:04 UTC, Spajro commented on src/main/java/input/Parser.java
> +    public static final Map<String, String> ShapeNameDictionaryPL = Map.ofEntries(
Mogłoby być private tho

2023-05-26 21:04 UTC, Spajro commented on src/test/java/commands/LanguageTest.java
> +        inputHandler.parseInput(String.format(Locale.US, "dodaj kwadrat bok %f", SQUARE_SIDE_VALUE));
Imho moglibyśmy wykorzystywać jedną instancję per test. Wtedy bylibyśmy niezależni od faktu, że Language jest statyczne

2023-05-27 11:58 UTC, Spajro approved these changes

2023-05-28 19:55 UTC, Spajro requested changes
Jak już jesteśmy przy toString to moglibyśmy od razu dodać do nich wypisywanie obwodu tam gdzie go brakuje

2023-05-28 19:55 UTC, Spajro commented on src/main/java/utils/Dictionary.java
> +        }
Może moglibyśmy trzymać dwie statyczne mapy z tłumaczeniami? Oszczędziłoby nam to przeszukiwania element po elemencie (które jest stosunkowo wolne) a drugą mapę można łatwo stworzyć poprzez `dictionary.entrySet()
       .stream()
       .collect(Collectors.toMap(Map.Entry::getValue, Map.Entry::getKey))`

2023-05-28 20:18 UTC, wilinska commented on src/main/java/utils/Dictionary.java
> +        }
tak, własnie nie byłam pewna co jest lepsze

2023-05-28 20:57 UTC, Spajro requested changes

2023-05-28 20:57 UTC, Spajro commented on src/main/java/shapes/Circle.java
> +                Format.parameterToString("circut", getCircuit()) +
Teraz mamy obwód dwa razy

2023-05-28 20:57 UTC, Spajro commented on src/main/java/utils/Dictionary.java
>      public static String toENG(String word) {
Może `fromPL`? Generalnie moglibyśmy zachować jakąś wspólną konwencję dla tych dwóch metod

2023-05-28 22:22 UTC, student317 approved these changes

2023-05-28 22:22 UTC, student317 approved these changes

2023-05-30 08:26 UTC, MarcinBieganek approved these changes

2023-05-30 14:21 UTC, Spajro approved these changes

2023-05-30 15:42 UTC, merged